version: '3'

services:
  akoranga-api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: npm run docker-dev
    volumes:
      - ./src/:/appdir/src
    ports:
      - "4567:4567"
    links:
      - mongodb

  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"